services:
  airontools-admin:
    image: airontools-admin # Nombre de la imagen
    container_name: airontools-admin # Nombre del contenedor
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    environment:
      NODE_ENV: production
      VITE_API_URL: "${VITE_API_URL}"
      PORT: "${VITE_PORT}"
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
