name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/airontools-admin:latest
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}
            VITE_PORT=${{ secrets.VITE_PORT }}
            VITE_AI_URL=${{ secrets.VITE_AI_URL }}

      - name: Run Docker Container
        run: |
          docker run -d \
            --name airontools-admin \
            --env NODE_ENV=production \
            --env VITE_API_URL=${{ secrets.VITE_API_URL }} \
            --env PORT=${{ secrets.VITE_PORT }} \
            --env VITE_AI_URL=${{ secrets.VITE_AI_URL }} \
            -p ${{ secrets.VITE_PORT }}:${{ secrets.VITE_PORT }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/airontools-admin:latest
